#!/bin/sh -e
# Copyright (c) 2015 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is sourced from main.sh to update distro-specific defaults.
# It must set at least ARCH and MIRROR if not already specified.

if [ -z "$ARCH" ]; then
    ARCH="`uname -m`"
fi

case "$ARCH" in
x86 | i?86) ARCH="i586";;
x86_64 | amd64) ARCH="x86_64";;
armv*) ARCH="armv7hl";;
aarch64 | arm64) ARCH="aarch64";;
*) error 2 "Invalid architecture '$ARCH'.";;
esac

if [ -z "$MIRROR" ]; then
    if [ "$ARCH" = 'amd64' -o "$ARCH" = 'i586' ]; then
        MIRROR="${CROUTON_MIRROR_opensuse_x86:-http://download.opensuse.org/tumbleweed/repo/oss/}"
    else
        MIRROR="${CROUTON_MIRROR_opensuse_arm:-http://download.opensuse.org/ports/armv7hl/tumbleweed/repo/oss/}"
    fi
fi

